// Graph models — shared sample network + per-model solver step data
export function graphSample(id){
    const nodes=[{id:'A',x:64,y:150},{id:'B',x:210,y:58},{id:'C',x:196,y:246},{id:'D',x:360,y:92},{id:'E',x:352,y:230},{id:'F',x:496,y:150}];
    const edges=[{a:'A',b:'B',w:4},{a:'A',b:'C',w:2},{a:'B',b:'C',w:5},{a:'B',b:'D',w:10},{a:'B',b:'E',w:7},{a:'C',b:'E',w:3},{a:'E',b:'D',w:4},{a:'D',b:'F',w:11},{a:'E',b:'F',w:8}];
    const cfg={shortestpath:['cost',1,'Edge numbers are costs — the solver finds the cheapest route from the start to the goal.'],maxflow:['capacity',1,'Edge numbers are capacities — the solver pushes the most flow from source to sink.'],mincostflow:['cost',1,'Edge numbers are unit costs — the solver routes the required amount as cheaply as possible.'],tsp:['distance',0,'Edge numbers are distances — the tour visits every node once and returns.'],vrp:['distance',0,'Edge numbers are distances — stops are split across the fleet within capacity.']}[id]||['cost',1,''];
    return{nodes,edges,from:'A',to:'F',w:cfg[0],ft:!!cfg[1],hint:cfg[2],veh:2};}
export const GN={A:[64,150],B:[210,58],C:[196,246],D:[360,92],E:[352,230],F:[496,150]};
export const GEC=[['A','B',4],['A','C',2],['B','C',5],['B','D',10],['B','E',7],['C','E',3],['E','D',4],['D','F',11],['E','F',8]];
export const GR={
  shortestpath:{badge:['✓ EXACT OPTIMUM','ok'],method:'Dijkstra · 6 nodes settled',objPre:'min Z =',objVal:'13',objNote:'total cost A → F — every alternative route was priced and lost',
   tHead:['NODE','DIST','VIA','STATUS'],
   legend:[{sw:'width:12px;height:12px;border-radius:50%;background:color-mix(in oklab, var(--accent) 15%, var(--surface));box-shadow:inset 0 0 0 1.5px var(--accent)',t:'settled — distance is final'},{sw:'width:11px;height:11px;border-radius:50%;border:1.5px dashed var(--accent)',t:'frontier'},{sw:'width:16px;border-top:2px dashed var(--accent)',t:'edge relaxed this step'},{sw:'width:16px;border-top:2.5px solid var(--accent)',t:'shortest path'}],
   steps:[
    {label:'Initialise',sub:'settle A · d = 0',zt:'0',meta:['d(A) = 0','B → 4','C → 2'],note:'Every node starts at ∞ except the start. A settles at 0 and its edges are relaxed: B drops to 4 and C to 2. Dijkstra always advances from the cheapest unsettled node.',g:{cur:'A',front:['B','C'],erelax:[['A','B'],['A','C']],nlab:{A:'0',B:'4',C:'2',D:'∞',E:'∞',F:'∞'}},rows:[{c:['A','0','—','settled'],hi:1},{c:['B','4','A','frontier']},{c:['C','2','A','frontier']},{c:['D','∞','—','']},{c:['E','∞','—','']},{c:['F','∞','—','']}]},
    {label:'Settle C',sub:'cheapest frontier · d = 2',zt:'2',meta:['d(C) = 2','E → 5','B keeps 4'],note:'C (2) beats B (4), so it settles first. Relaxing its edges puts E on the frontier at 2 + 3 = 5; reaching B through C would cost 7, so B keeps its direct 4.',g:{cur:'C',settled:['A'],front:['B','E'],erelax:[['C','E'],['B','C']],nlab:{A:'0',B:'4',C:'2',D:'∞',E:'5',F:'∞'}},rows:[{c:['A','0','—','settled']},{c:['C','2','A','settled'],hi:1},{c:['B','4','A','frontier']},{c:['E','5','C','frontier']},{c:['D','∞','—','']},{c:['F','∞','—','']}]},
    {label:'Settle B',sub:'d = 4 · D joins the frontier',zt:'4',meta:['d(B) = 4','D → 14','E keeps 5'],note:'B settles at its direct distance. D enters the frontier at 4 + 10 = 14 — expensive, but the best known so far. E via B would cost 11, so it keeps 5.',g:{cur:'B',settled:['A','C'],front:['D','E'],erelax:[['B','D'],['B','E']],nlab:{A:'0',B:'4',C:'2',D:'14',E:'5',F:'∞'}},rows:[{c:['A','0','—','settled']},{c:['C','2','A','settled']},{c:['B','4','A','settled'],hi:1},{c:['E','5','C','frontier']},{c:['D','14','B','frontier']},{c:['F','∞','—','']}]},
    {label:'Settle E',sub:'d = 5 · two improvements',zt:'5',meta:['d(E) = 5','D 14 → 9','F → 13'],note:'E is the step that pays off: it re-prices D down from 14 to 9 and gives F its first label, 5 + 8 = 13.',g:{cur:'E',settled:['A','C','B'],front:['D','F'],erelax:[['E','D'],['E','F']],nlab:{A:'0',B:'4',C:'2',D:'9',E:'5',F:'13'}},rows:[{c:['A','0','—','settled']},{c:['C','2','A','settled']},{c:['B','4','A','settled']},{c:['E','5','C','settled'],hi:1},{c:['D','9','E','frontier']},{c:['F','13','E','frontier']}]},
    {label:'Settle D',sub:'d = 9 · nothing improves',zt:'9',meta:['d(D) = 9','F keeps 13'],note:'D settles at 9, but continuing to F would cost 9 + 11 = 20 — worse than the 13 already on the table. Nothing changes.',g:{cur:'D',settled:['A','C','B','E'],front:['F'],erelax:[['D','F']],nlab:{A:'0',B:'4',C:'2',D:'9',E:'5',F:'13'}},rows:[{c:['A','0','—','settled']},{c:['C','2','A','settled']},{c:['B','4','A','settled']},{c:['E','5','C','settled']},{c:['D','9','E','settled'],hi:1},{c:['F','13','E','frontier']}]},
    {label:'Target settled',sub:'A → C → E → F proven',zt:'✓',meta:['d(F) = 13','no cheaper route exists'],note:'F is now the cheapest frontier node, so 13 is provably minimal — every other route was priced and lost. Walking the via-pointers back gives A → C → E → F.',g:{cur:'F',settled:['A','C','B','E','D'],epath:[['A','C'],['C','E'],['E','F']],nlab:{A:'0',B:'4',C:'2',D:'9',E:'5',F:'13'}},rows:[{c:['A','0','—','on path'],hi:1},{c:['C','2','A','on path'],hi:1},{c:['E','5','C','on path'],hi:1},{c:['F','13','E','on path'],hi:1},{c:['B','4','A','settled']},{c:['D','9','E','settled']}]}
   ],
   ans:{head:'ROUTE',tHead:['LEG','COST','CUM'],rows:[{c:['A → C','2','2'],hi:1},{c:['C → E','3','5'],hi:1},{c:['E → F','8','13'],hi:1}],note:'Three legs, total 13. The runner-up route (A → B → E → F) costs 19 — 46% longer.',g:{epath:[['A','C'],['C','E'],['E','F']],nlab:{A:'0',C:'2',E:'5',F:'13'}}},
   insight:[
    {t:'Distances to every node',p:'Dijkstra prices the whole network on the way to F — these come free with the answer.',rows:[['A — start','0'],['C','2'],['B','4'],['E','5'],['D','9'],['F — target','13']]},
    {t:'How stable is the route?',p:'How far each leg can rise in cost before a different route wins.',rows:[['A – C · now 2','up to 8'],['C – E · now 3','up to 9'],['E – F · now 8','up to 15']],foot:'Beyond those, A → B → E → F (19) or A → C → E → D → F (20) takes over.'},
    {t:'Runner-up routes',p:'The next-best alternatives, already fully priced by the search.',rows:[['A → B → E → F','19'],['A → C → E → D → F','20'],['A → B → D → F','25']]}
   ]},
  maxflow:{badge:['✓ EXACT OPTIMUM','ok'],method:'Edmonds–Karp · 2 augmenting paths',objPre:'max F =',objVal:'6',objNote:'units of flow A → F — capped by the cut at the source',
   tHead:['EDGE','FLOW','CAP'],
   legend:[{sw:'width:16px;border-top:2.5px solid var(--accent)',t:'augmenting path'},{sw:'width:16px;border-top:2px dashed var(--warn)',t:'min cut'},{sw:'',t:'edge labels are flow / capacity'}],
   steps:[
    {label:'Augmenting path 1',sub:'A → B → D → F · push 4',zt:'4',meta:['bottleneck 4 at A→B','F = 4'],note:'Breadth-first search finds the shortest path with spare capacity: A → B → D → F. Its tightest edge is A → B at 4, so 4 units flow along the whole path.',g:{epath:[['A','B'],['B','D'],['D','F']],elab:{'A-B':'4/4','A-C':'0/2','B-C':'0/5','B-D':'4/10','B-E':'0/7','C-E':'0/3','E-D':'0/4','D-F':'4/11','E-F':'0/8'}},rows:[{c:['A → B','4','4'],hi:1},{c:['A → C','0','2']},{c:['B → C','0','5']},{c:['B → D','4','10'],hi:1},{c:['B → E','0','7']},{c:['C → E','0','3']},{c:['E → D','0','4']},{c:['D → F','4','11'],hi:1},{c:['E → F','0','8']}]},
    {label:'Augmenting path 2',sub:'A → C → E → F · push 2',zt:'6',meta:['bottleneck 2 at A→C','F = 6'],note:'The next search routes around the saturated A → B: A → C → E → F carries 2 more units, limited by A → C. Total flow is now 6.',g:{epath:[['A','C'],['C','E'],['E','F']],elab:{'A-B':'4/4','A-C':'2/2','B-C':'0/5','B-D':'4/10','B-E':'0/7','C-E':'2/3','E-D':'0/4','D-F':'4/11','E-F':'2/8'}},rows:[{c:['A → B','4','4']},{c:['A → C','2','2'],hi:1},{c:['B → C','0','5']},{c:['B → D','4','10']},{c:['B → E','0','7']},{c:['C → E','2','3'],hi:1},{c:['E → D','0','4']},{c:['D → F','4','11']},{c:['E → F','2','8'],hi:1}]},
    {label:'Min-cut certificate',sub:'no augmenting path left',zt:'✓',meta:['cut {A→B, A→C} = 6','max-flow = min-cut'],note:'Both edges out of A are saturated, so no residual path reaches F. Those two edges form a cut of capacity 4 + 2 = 6 — equal to the flow, which proves 6 is the maximum.',g:{ecut:[['A','B'],['A','C']],elab:{'A-B':'4/4','A-C':'2/2','B-C':'0/5','B-D':'4/10','B-E':'0/7','C-E':'2/3','E-D':'0/4','D-F':'4/11','E-F':'2/8'}},rows:[{c:['A → B','4','4'],hi:1},{c:['A → C','2','2'],hi:1},{c:['B → C','0','5']},{c:['B → D','4','10']},{c:['B → E','0','7']},{c:['C → E','2','3']},{c:['E → D','0','4']},{c:['D → F','4','11']},{c:['E → F','2','8']}]}
   ],
   ans:{head:'EDGE FLOWS',tHead:['EDGE','FLOW','CAP'],rows:[{c:['A → B','4','4']},{c:['B → D','4','10']},{c:['D → F','4','11']},{c:['A → C','2','2']},{c:['C → E','2','3']},{c:['E → F','2','8']},{c:['Σ into F','6','—'],hi:1}],note:'Six of nine edges carry flow. The cut {A → B, A → C} caps the network at 6 — certified optimal by max-flow = min-cut.',g:{epath:[['A','B'],['B','D'],['D','F'],['A','C'],['C','E'],['E','F']],elab:{'A-B':'4/4','A-C':'2/2','B-C':'0/5','B-D':'4/10','B-E':'0/7','C-E':'2/3','E-D':'0/4','D-F':'4/11','E-F':'2/8'}}},
   insight:[
    {t:'The bottleneck — min cut',p:'Edges A → B and A → C form the tightest barrier between source and sink.',rows:[['A → B','4'],['A → C','2'],['Cut capacity','6']],foot:'Capacity added anywhere else in the network is wasted until this cut grows.'},
    {t:'Where +1 capacity helps',p:'The effect of one extra unit of capacity, edge by edge.',rows:[['A → C +1','flow 6 → 7'],['A → B +1','flow 6 → 7'],['Any other edge +1','no change']]},
    {t:'Slack in the network',p:'Unused capacity downstream — headroom once the source cut is widened.',rows:[['B → D','6 free'],['D → F','7 free'],['B → E','7 free'],['E → F','6 free']]}
   ]},
  mincostflow:{badge:['✓ EXACT OPTIMUM','ok'],method:'Successive shortest paths · 2 iterations · 6 units',objPre:'min Z =',objVal:'102',objNote:'total cost of routing 6 units A → F',
   tHead:['EDGE','UNITS','C/UNIT','COST'],
   legend:[{sw:'width:16px;border-top:2.5px solid var(--accent)',t:'cheapest path'},{sw:'width:16px;border-top:2.5px solid var(--blue)',t:'second path'},{sw:'',t:'u = units routed on the edge'}],
   steps:[
    {label:'Cheapest path',sub:'A → C → E → F · 13 per unit',zt:'26',meta:['unit cost 13','send 2 — A→C is full','Z = 26'],note:'Edge numbers are costs per unit, so the solver repeatedly sends flow down the cheapest residual path. A → C → E → F costs 2 + 3 + 8 = 13 per unit and carries 2 units before A → C saturates: cost so far 26.',g:{epath:[['A','C'],['C','E'],['E','F']],elab:{'A-C':'2u','C-E':'2u','E-F':'2u'}},rows:[{c:['A → C','2','2','4'],hi:1},{c:['C → E','2','3','6'],hi:1},{c:['E → F','2','8','16'],hi:1},{c:['Σ so far','2 units','','26']}]},
    {label:'Next cheapest',sub:'A → B → E → F · 19 per unit',zt:'102',meta:['unit cost 19','send 4','Z 26 → 102'],note:'With A → C full, the cheapest remaining path is A → B → E → F at 4 + 7 + 8 = 19 per unit. The outstanding 4 units take it: 26 + 4 × 19 = 102.',g:{epath:[['A','B'],['B','E'],['E','F']],elab:{'A-C':'2u','C-E':'2u','A-B':'4u','B-E':'4u','E-F':'6u'}},rows:[{c:['A → C','2','2','4']},{c:['C → E','2','3','6']},{c:['A → B','4','4','16'],hi:1},{c:['B → E','4','7','28'],hi:1},{c:['E → F','6','8','48'],hi:1},{c:['Σ','6 units','','102']}]},
    {label:'Demand met',sub:'6 units routed · optimal',zt:'✓',meta:['6 / 6 units','no cheaper residual path'],note:'All 6 units have arrived, and every residual path now costs at least as much as the ones used — successive shortest paths guarantees the plan is the cheapest possible.',g:{epath:[['A','C'],['C','E'],['E','F']],epath2:[['A','B'],['B','E']],elab:{'A-C':'2u','C-E':'2u','A-B':'4u','B-E':'4u','E-F':'6u'}},rows:[{c:['A → C','2','2','4']},{c:['C → E','2','3','6']},{c:['A → B','4','4','16']},{c:['B → E','4','7','28']},{c:['E → F','6','8','48']},{c:['Σ','6 units','','102'],hi:1}]}
   ],
   ans:{head:'FLOW & COST',tHead:['EDGE','UNITS','C/UNIT','COST'],rows:[{c:['A → C','2','2','4']},{c:['C → E','2','3','6']},{c:['A → B','4','4','16']},{c:['B → E','4','7','28']},{c:['E → F','6','8','48']},{c:['Σ','6 units','','102'],hi:1}],note:'Both paths funnel through E → F — the corridor every cheap route shares. It carries all 6 units at cost 48, nearly half the total.',g:{epath:[['A','C'],['C','E'],['E','F']],epath2:[['A','B'],['B','E']],elab:{'A-C':'2u','C-E':'2u','A-B':'4u','B-E':'4u','E-F':'6u'}}},
   insight:[
    {t:'Marginal cost is rising',p:'Each extra unit costs more than the last as cheap capacity runs out.',rows:[['Units 1–2','13 / unit'],['Units 3–6','19 / unit'],['A 7th unit would cost','25 / unit']],foot:'The 7th unit would ride A → B → D → F.'},
    {t:'Binding capacities',p:'Both saturated edges sit at the source — widening them lowers the marginal cost.',rows:[['A → C','2 / 2 used'],['A → B','4 / 4 used']]},
    {t:'Cost breakdown',p:'What each path contributes to the bill.',rows:[['A→C→E→F · 2u @ 13','26'],['A→B→E→F · 4u @ 19','76'],['Total','102']]}
   ]},
  tsp:{badge:['≈ HEURISTIC · GAP ≤ 2.7%','warn'],method:'Nearest neighbour + 2-opt · 6 stops',objPre:'min Z =',objVal:'38',objNote:'total tour length — a 1-tree bound proves nothing beats 37',
   tHead:['LEG','DIST','CUM'],
   legend:[{sw:'width:16px;border-top:2.5px solid var(--accent)',t:'current tour'},{sw:'width:16px;border-top:1.5px dashed var(--mut)',t:'road not in tour'}],
   steps:[
    {label:'Construct tour',sub:'nearest neighbour from A',zt:'44',meta:['greedy build','Z = 44'],note:'Start at A and always ride to the nearest unvisited stop: A → C → E → D → B → F → A. Greedy is fast but short-sighted — the last two legs are the longest in the tour.',g:{epath:[['A','C'],['C','E'],['E','D'],['D','B'],['B','F'],['F','A']],extra:[['B','F',16],['F','A',9]]},rows:[{c:['A → C','2','2']},{c:['C → E','3','5']},{c:['E → D','4','9']},{c:['D → B','10','19']},{c:['B → F','16','35'],hi:1},{c:['F → A','9','44'],hi:1}]},
    {label:'2-opt · first swap',sub:'drop D → B and F → A',zt:'40',meta:['saves 4','Z 44 → 40'],note:'Delete legs D → B and F → A, reverse the segment between them and reconnect: D → F and B → A take their place, trading 19 of distance for 15.',g:{epath:[['A','C'],['C','E'],['E','D'],['D','F'],['F','B'],['B','A']],extra:[['B','F',16],['F','A',9]]},rows:[{c:['A → C','2','2']},{c:['C → E','3','5']},{c:['E → D','4','9']},{c:['D → F','11','20'],hi:1},{c:['F → B','16','36']},{c:['B → A','4','40'],hi:1}]},
    {label:'2-opt · second swap',sub:'drop E → D and F → B',zt:'38',meta:['saves 2','Z 40 → 38'],note:'The second swap removes the 16-length leg F → B entirely: E → F and D → B reconnect the tour, saving 2 more and leaving it on short roads only.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','D'],['D','B'],['B','A']]},rows:[{c:['A → C','2','2']},{c:['C → E','3','5']},{c:['E → F','8','13'],hi:1},{c:['F → D','11','24']},{c:['D → B','10','34'],hi:1},{c:['B → A','4','38']}]},
    {label:'Local optimum',sub:'no improving swap left',zt:'✓',meta:['1-tree bound 37','gap ≤ 2.7%'],note:'Every remaining 2-opt move makes the tour longer. A 1-tree lower bound proves no tour can beat 37, so 38 is at most 2.7% from optimal.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','D'],['D','B'],['B','A']]},rows:[{c:['A → C','2','2']},{c:['C → E','3','5']},{c:['E → F','8','13']},{c:['F → D','11','24']},{c:['D → B','10','34']},{c:['B → A','4','38']}]}
   ],
   ans:{head:'TOUR ORDER',tHead:['LEG','DIST','CUM'],rows:[{c:['A → C','2','2']},{c:['C → E','3','5']},{c:['E → F','8','13']},{c:['F → D','11','24']},{c:['D → B','10','34']},{c:['B → A','4','38']}],note:'A → C → E → F → D → B → A, 38 total. If certainty matters, branch & bound is feasible at 6 stops — but the bound already pins the gap under 3%.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','D'],['D','B'],['B','A']]}},
   insight:[
    {t:'How good is 38?',p:'The bound says no tour beats 37 — the heuristic answer is near-certainly optimal.',rows:[['2-opt tour','38'],['1-tree lower bound','37'],['Worst-case gap','2.7%']],foot:'Run exact solve (branch & bound) if you need the certificate.'},
    {t:'Longest legs',p:'These dominate the tour — fixed geography, not solver error.',rows:[['F → D','11'],['D → B','10'],['E → F','8']]}
   ]},
  vrp:{badge:['≈ HEURISTIC · SAVINGS','warn'],method:'Clarke–Wright savings + 2-opt · 2 vehicles · capacity 12',objPre:'min Z =',objVal:'52',objNote:'total distance for both routes — down 28% from the radial start',
   tHead:['ROUTE','LOAD','DIST'],
   legend:[{sw:'width:16px;border-top:2.5px solid var(--accent)',t:'vehicle 1'},{sw:'width:16px;border-top:2.5px solid var(--blue)',t:'vehicle 2'},{sw:'width:16px;border-top:1.5px dashed var(--mut)',t:'unused direct road'}],
   steps:[
    {label:'Radial start',sub:'one round trip per stop',zt:'72',meta:['5 round trips','Z = 72'],note:'Every stop begins as its own out-and-back from depot A: 2 × (4 + 2 + 12 + 5 + 13) = 72. All the savings come from chaining stops together.',g:{epath:[['A','B'],['A','C'],['A','D'],['A','E'],['A','F']],extra:[['A','D',12],['A','E',5],['A','F',13]]},rows:[{c:['A → B → A','3','8']},{c:['A → C → A','2','4']},{c:['A → D → A','6','24']},{c:['A → E → A','2','10']},{c:['A → F → A','3','26']}]},
    {label:'Merge C – E – F',sub:'largest savings first',zt:'58',meta:['s(E,F) = 10 · s(C,E) = 4','Z 72 → 58'],note:'Chaining E → F saves 10 and C → E another 4, so vehicle 1 runs A → C → E → F → A (load 7 of 12). B and D still ride alone.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','A']],epath2:[['A','B'],['A','D']],extra:[['A','D',12],['A','E',5],['A','F',13]]},rows:[{c:['A → C → E → F → A','7 / 12','26'],hi:1},{c:['A → B → A','3','8']},{c:['A → D → A','6','24']}]},
    {label:'Merge B – D',sub:'s(B,D) = 6',zt:'52',meta:['s(B,D) = 6','Z 58 → 52'],note:'Merging B and D saves 6 more: vehicle 2 runs A → B → D → A (load 9 of 12). No further merge fits within capacity.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','A']],epath2:[['A','B'],['B','D'],['D','A']],extra:[['A','D',12],['A','E',5],['A','F',13]]},rows:[{c:['A → C → E → F → A','7 / 12','26']},{c:['A → B → D → A','9 / 12','26'],hi:1}]},
    {label:'Capacity + 2-opt check',sub:'no improvement found',zt:'✓',meta:['loads 7 & 9 of 12','no improving move'],note:'Reversing either route or swapping stops between vehicles only adds distance. The savings solution stands at 52 — a 28% cut from the radial start.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','A']],epath2:[['A','B'],['B','D'],['D','A']],extra:[['A','D',12],['A','E',5],['A','F',13]]},rows:[{c:['A → C → E → F → A','7 / 12','26']},{c:['A → B → D → A','9 / 12','26']},{c:['Σ 2 vehicles','16','52'],hi:1}]}
   ],
   ans:{head:'ROUTES',tHead:['ROUTE','LOAD','DIST'],rows:[{c:['A → C → E → F → A','7 / 12','26']},{c:['A → B → D → A','9 / 12','26']},{c:['Σ 2 vehicles','16','52'],hi:1}],note:'Total demand is 16, more than one vehicle’s 12-unit capacity — two routes is the minimum feasible fleet.',g:{epath:[['A','C'],['C','E'],['E','F'],['F','A']],epath2:[['A','B'],['B','D'],['D','A']],extra:[['A','D',12],['A','E',5],['A','F',13]]}},
   insight:[
    {t:'Fleet balance',p:'Both loads sit comfortably under the 12-unit capacity.',rows:[['Vehicle 1 · C, E, F','7 / 12'],['Vehicle 2 · B, D','9 / 12']],foot:'Total demand 16 rules out a single vehicle.'},
    {t:'Savings captured',p:'Clarke–Wright recovered the big merges in two moves.',rows:[['Radial start','72'],['After merges','52'],['Saved','20 · −28%']]}
   ]}
  };
